### ISSUE TITLE
invalid memory address when mock a call which use pgx.Conn?

### ISSUE THREAD

**Issue by Spaceman2019** [pashagolub/pgxmock#20]
I have the following funtion:

```go
func GetUserByID(ctx context.Context, db *pgx.Conn, id int64) (*User, error) {
	var user User
	sql, args, err := sq.Select("id, userid, name, email").
		From("user").
		Where(sq.Eq{"id": id}).
		PlaceholderFormat(sq.Dollar).
		ToSql()
	if err != nil {
		return nil, err
	}
	err = db.QueryRow(ctx, sql, args...).Scan(&user.ID, &user.Userid, &user.Name, &user.Email)
	if err != nil {
		return nil, err
	}
	fmt.Println("Get User by ID")
	return &user, nil
}
```
Now I want to mock the call with:

```go
mock, err := pgxmock.NewConn(pgxmock.QueryMatcherOption(pgxmock.QueryMatcherEqual))
if err != nil {
	t.Fatalf("an error '%s' was not expected when opening a stub database connection", err)
}
defer mock.Close(context.Background())
userid, _ := uuid.NewV4()
rows := pgxmock.NewRows([]string{"id", "userid", "name", "email"}).
	AddRow(int64(17), userid, "Testuser", "abc@xyz.com")
mock.ExpectBegin()
mock.ExpectQuery("SELECT id, userid, name, email FROM user WHERE id = $1").
	WithArgs(int64(17)).
	WillReturnRows(rows).
	WillReturnError(nil)
mock.ExpectCommit()
result, err := GetUserByID(context.Background(), mock.Conn(), 17)
require.NoError(t, err)
```

But when I run the test I got the following error:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0xaa9cc9]
```

How can I mock the call without using a transaction? It's only a SELECT, so I do not need a transaction.

Thanks

**Comment by pashagolub** [comment]
hello.

You don't need to 
`WillReturnError(nil)`

Either return rows, or error, but not both

**Comment by pashagolub** [comment]
And you don't need `ExpectBegin()` and `ExpectCommit()` if you are not using transactions

**Comment by Spaceman2019** [comment]
I have change the test to:
 
```go
	rows := pgxmock.NewRows([]string{"id", "userid", "name", "email"}).
		AddRow(int64(17), userid, "Testuser", "abc@xyz.com")

	mock.ExpectQuery("SELECT id, userid, name, email FROM user WHERE id = $1").
		WithArgs(int64(17)).
		WillReturnRows(rows)

	result, err := GetUserByID(context.Background(), mock.Conn(), 17)

```

But I got the same error:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0xe79cc9]

goroutine 19 [running]:
testing.tRunner.func1.2(0xef0c60, 0x1165b80)
	C:/Go/src/testing/testing.go:1144 +0x345
testing.tRunner.func1(0xc000084480)
	C:/Go/src/testing/testing.go:1147 +0x4b6
panic(0xef0c60, 0x1165b80)
	C:/Go/src/runtime/panic.go:965 +0x1c7
github.com/jackc/pgx/v4.(*Conn).Query(0x0, 0xfb3a70, 0xc00009e0d0, 0xc0000b8300, 0x36, 0xc0000894f0, 0x1, 0x1, 0x0, 0x14, ...)
	C:/Users/xxx/go/src/xxx.de/testpgxmock/vendor/github.com/jackc/pgx/v4/conn.go:570 +0x49
github.com/jackc/pgx/v4.(*Conn).QueryRow(...)
	C:/Users/xxx/go/src/xxx.de/testpgxmock/vendor/github.com/jackc/pgx/v4/conn.go:680
xxx.de/testprojects/testpgxmock.GetUserByID(0xfb3a70, 0xc00009e0d0, 0x0, 0x11, 0x1, 0x14, 0x0)
	C:/Users/xxx/go/src/xxx.de/testpgxmock/user.go:52 +0x42c
xxx.de/testprojects/testpgxmock.TestGetUserByIDSuccess(0xc000084480)
	C:/Users/xxx/go/src/xxx.de/testpgxmock/user_test.go:76 +0x579
testing.tRunner(0xc000084480, 0xf64290)
	C:/Go/src/testing/testing.go:1194 +0xef
created by testing.(*T).Run
	C:/Go/src/testing/testing.go:1239 +0x2b3
```

Line 52 in user.go starts with ```err = db.queryRow```

**Comment by pashagolub** [comment]
Oh, sorry. I didn't notice your function. You're using `db *pgx.Conn`, but you should use interface. Please check example:
https://github.com/pashagolub/pgxmock/blob/master/examples/basic/basic.go

There is no way we can hijack the real `pgx.Conn`

**Comment by pashagolub** [comment]
`mock.Conn()` is present only for compatibility reasons with `pgx.Conn` and `pgx.Pool`. 

I should probably raise an error in it to avoid such misunderstandings.

**Comment by Spaceman2019** [comment]
Ok, than I must change the signiture from ```db *pgx.Conn``` to ```tx pgx.Tx```.

**Comment by pashagolub** [comment]
That might work! 👍
